openapi: 3.0.0
info:
  version: latest
  title: Puppet Reporter
  description: This is the API documentation for the Puppet Reporter application

tags:
  - name: reports
    description: Operations related to reports

paths:
  /upload:
    post:
      operationId: uploadReport
      tags:
        - reports
      summary: Upload a report
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Report uploaded successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid file format
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An error occurred while processing the report

  /reports:
    get:
      operationId: getReports
      tags:
        - reports
      summary: Get all reports
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/report_response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An error occurred while fetching the reports

  /reports/{hash}:
    get:
      operationId: getReport
      tags:
        - reports
      summary: Get a report by hash
      parameters:
        - name: hash
          in: path
          required: true
          description: The hash of the report
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/report_details'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Report not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An error occurred while fetching the report

components:
  schemas:
    report_response:
      type: object
      required:
        - reports
        - total
      properties:
        reports:
          type: array
          items:
            $ref: '#/components/schemas/report'
        total:
          type: integer
          format: int64
          example: 10

    report:
      type: object
      properties:
        hash:
          type: string
          example: 3b0e8b4e1
        host:
          type: string
          example: 192.168.0.1
        puppet_version:
          type: number
          format: float
          example: 8.6
        environment:
          type: string
          example: PRODUCTION
        status:
          type: string
          example: CHANGED
        executed_at:
          type: string
          format: date-time
          example: 2021-07-01T12:00:00Z
        runtime_seconds:
          type: integer
          format: int64
          example: 10.5
        total_failed:
          type: integer
          format: int64
          example: 2
        total_changed:
          type: integer
          format: int64
          example: 5
        total_skipped:
          type: integer
          format: int64
          example: 1
        total_resources:
          type: integer
          format: int64
          example: 100

    report_details:
      type: object
      properties:
        report:
          $ref: '#/components/schemas/report'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/resource'
        logs:
          type: array
          items:
            $ref: '#/components/schemas/log_message'

    resource:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/status'
        name:
          type: string
          example: apt-update
        type:
          type: string
          example: Exec
        file:
          type: string
          example: /opt/puppet/site/default_config/manifests/init.pp
        line:
          type: integer
          format: int64
          example: 10

    status:
      type: string
      enum:
        - CHANGED
        - FAILED
        - SKIPPED
        - UNCHANGED

    log_message:
      type: object
      properties:
        message:
          type: string
          example: 'Example message'
