openapi: 3.0.0
info:
  version: latest
  title: Puppet Reporter
  description: This is the API documentation for the Puppet Reporter application

tags:
  - name: reports
    description: Operations related to reports

paths:
  /upload:
    post:
      operationId: uploadReport
      tags:
        - reports
      summary: Upload a report
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/report_details'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../../../vendor/github.com/jacobbrewer1/uhttp/common/common.yaml#/components/schemas/error_message'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '../../../../vendor/github.com/jacobbrewer1/uhttp/common/common.yaml#/components/schemas/error_message'

  /reports:
    get:
      operationId: getReports
      tags:
        - reports
      summary: Get all reports
      parameters:
        - $ref: '../../../../vendor/github.com/jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/limit_param'
        - $ref: '../../../../vendor/github.com/jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/last_value'
        - $ref: '../../../../vendor/github.com/jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/last_id'
        - $ref: '../../../../vendor/github.com/jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/sort_by'
        - $ref: '../../../../vendor/github.com/jacobbrewer1/pagefilter/common/common.yaml#/components/parameters/sort_direction'
        - $ref: '#/components/parameters/query_host'
        - $ref: '#/components/parameters/query_environment'
        - $ref: '#/components/parameters/query_state'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/report_response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../../../vendor/github.com/jacobbrewer1/uhttp/common/common.yaml#/components/schemas/message'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '../../../../vendor/github.com/jacobbrewer1/uhttp/common/common.yaml#/components/schemas/error_message'

  /reports/{hash}:
    get:
      operationId: getReport
      tags:
        - reports
      summary: Get a report by hash
      parameters:
        - name: hash
          in: path
          required: true
          description: The hash of the report
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/report_details'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../../../vendor/github.com/jacobbrewer1/uhttp/common/common.yaml#/components/schemas/message'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '../../../../vendor/github.com/jacobbrewer1/uhttp/common/common.yaml#/components/schemas/message'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '../../../../vendor/github.com/jacobbrewer1/uhttp/common/common.yaml#/components/schemas/error_message'

components:
  parameters:
    query_environment:
      name: environment
      in: query
      description: Filter by environment
      schema:
        type: string
    query_host:
      name: host
      in: query
      description: Filter by host
      schema:
        type: string
    query_state:
      name: state
      in: query
      description: Filter by status
      schema:
        $ref: '#/components/schemas/status'

  schemas:
    report_response:
      type: object
      required:
        - reports
        - total
      properties:
        reports:
          type: array
          items:
            $ref: '#/components/schemas/report'
        total:
          type: integer
          format: int64
          example: 10

    report:
      type: object
      required:
        - id
        - hash
        - host
        - puppet_version
        - environment
        - status
        - executed_at
        - runtime_seconds
        - total_failed
        - total_changed
        - total_skipped
        - total_resources
      properties:
        id:
          type: integer
          format: int64
          example: 1
        hash:
          type: string
          example: 3b0e8b4e1
        host:
          type: string
          example: 192.168.0.1
        puppet_version:
          type: number
          format: float
          example: 8.6
        environment:
          type: string
          example: PRODUCTION
        status:
          type: string
          example: CHANGED
        executed_at:
          type: string
          format: date-time
          example: 2021-07-01T12:00:00Z
        runtime_seconds:
          type: integer
          format: int64
          example: 10.5
        total_failed:
          type: integer
          format: int64
          example: 2
        total_changed:
          type: integer
          format: int64
          example: 5
        total_skipped:
          type: integer
          format: int64
          example: 1
        total_resources:
          type: integer
          format: int64
          example: 100

    report_details:
      type: object
      required:
        - report
        - resources
        - logs
      properties:
        report:
          $ref: '#/components/schemas/report'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/resource'
        logs:
          type: array
          items:
            $ref: '#/components/schemas/log_message'

    resource:
      type: object
      required:
        - status
        - name
        - type
        - file
        - line
      properties:
        status:
          $ref: '#/components/schemas/status'
        name:
          type: string
          example: apt-update
        type:
          type: string
          example: Exec
        file:
          type: string
          example: /opt/puppet/site/default_config/manifests/init.pp
        line:
          type: integer
          format: int64
          example: 10

    status:
      type: string
      enum:
        - CHANGED
        - FAILED
        - SKIPPED
        - UNCHANGED

    log_message:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Example message'
