// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// LogMessage defines the model for log_message.
type LogMessage struct {
	Message *string `json:"message,omitempty"`
}

// Report defines the model for report.
type Report struct {
	Environment    *string    `json:"environment,omitempty"`
	ExecutedAt     *time.Time `json:"executed_at,omitempty"`
	Hash           *string    `json:"hash,omitempty"`
	Host           *string    `json:"host,omitempty"`
	PuppetVersion  *float32   `json:"puppet_version,omitempty"`
	RuntimeSeconds *int64     `json:"runtime_seconds,omitempty"`
	Status         *string    `json:"status,omitempty"`
	TotalChanged   *int64     `json:"total_changed,omitempty"`
	TotalFailed    *int64     `json:"total_failed,omitempty"`
	TotalResources *int64     `json:"total_resources,omitempty"`
	TotalSkipped   *int64     `json:"total_skipped,omitempty"`
}

// ReportDetails defines the model for report_details.
type ReportDetails struct {
	Logs      *[]LogMessage `json:"logs,omitempty"`
	Report    *Report       `json:"report,omitempty"`
	Resources *[]Resource   `json:"resources,omitempty"`
}

// ReportResponse defines the model for report_response.
type ReportResponse struct {
	Reports []Report `json:"reports"`
	Total   int64    `json:"total"`
}

// Resource defines the model for resource.
type Resource struct {
	File   *string `json:"file,omitempty"`
	Line   *int64  `json:"line,omitempty"`
	Name   *string `json:"name,omitempty"`
	Status *Status `json:"status,omitempty"`
	Type   *string `json:"type,omitempty"`
}

// Status defines the model for status.
type Status = string

// List of Status
const (
	Status_CHANGED   Status = "CHANGED"
	Status_FAILED    Status = "FAILED"
	Status_SKIPPED   Status = "SKIPPED"
	Status_UNCHANGED Status = "UNCHANGED"
)

// UploadReportMultipartBody defines parameters for UploadReport.
type UploadReportMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// UploadReportMultipartRequestBody defines body for UploadReport for multipart/form-data ContentType.
type UploadReportMultipartRequestBody UploadReportMultipartBody

// Temporary inclusion of type alias for backwards compatibility
type UploadReportJSONBody = UploadReportMultipartBody
