// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// PostUploadMultipartBody defines parameters for PostUpload.
type PostUploadMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// PostUploadMultipartRequestBody defines body for PostUpload for multipart/form-data ContentType.
type PostUploadMultipartRequestBody PostUploadMultipartBody
