// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jacobbrewer1/puppet-reporter/cmd"
	"github.com/jacobbrewer1/puppet-reporter/pkg/services/api"
)

// Injectors from wire.go:

func InitializeApp() (main.App, error) {
	context := getRootContext()
	serverInterface := api.NewService()
	v := getServerOptions()
	router, err := getRouter(serverInterface, v...)
	if err != nil {
		return nil, err
	}
	viper, err := getConfig()
	if err != nil {
		return nil, err
	}
	client, err := getVaultClient(viper)
	if err != nil {
		return nil, err
	}
	mainApp := main.newApp(context, router, client)
	return mainApp, nil
}
