// Code generated by mockery. DO NOT EDIT.

package api

import (
	pagefilter "github.com/jacobbrewer1/pagefilter"
	models "github.com/jacobbrewer1/puppet-reporter/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// ListLatestHosts provides a mock function with given fields: details, filters
func (_m *MockRepository) ListLatestHosts(details *pagefilter.PaginatorDetails, filters *ListLatestHostsFilters) (*pagefilter.PaginatedResponse[models.Report], error) {
	ret := _m.Called(details, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListLatestHosts")
	}

	var r0 *pagefilter.PaginatedResponse[models.Report]
	var r1 error
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *ListLatestHostsFilters) (*pagefilter.PaginatedResponse[models.Report], error)); ok {
		return rf(details, filters)
	}
	if rf, ok := ret.Get(0).(func(*pagefilter.PaginatorDetails, *ListLatestHostsFilters) *pagefilter.PaginatedResponse[models.Report]); ok {
		r0 = rf(details, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagefilter.PaginatedResponse[models.Report])
		}
	}

	if rf, ok := ret.Get(1).(func(*pagefilter.PaginatorDetails, *ListLatestHostsFilters) error); ok {
		r1 = rf(details, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
